# Specify base image

# Set the working directory to '/app' in the container. All subsequent commands will be issued relative to this directory.

# Copy over only package.json

# Install all dependencies

# Copy over all remaining source code

# Set the command to run when the container starts up